### ISSUE TITLE
When MongoDB is not installed on the system app just dies without any message.

### ISSUE THREAD

**Issue by azizur** [springernature/pa11y-webservice#7]
When MongoDB is not installed on the system there is no message and app just dies without any message.

I can see Docs say `pa11y-webservice also requires MongoDB to be installed and running.` However I think it would be good to have some in error handling for this.

**Comment by rowanmanning** [comment]
Hi @azizur, yeah it would be useful to get a descriptive error report here. I can look into it, also happy to accept PRs if you're interested in working on it.

**Comment by rowanmanning** [comment]
This should be fixed in `1.7.0`
